[tool.poetry]
name = "pyi18n_new"
version = "1.0.1"
description = "Advanced i18n realization"
authors = ["Daniel Zakharov <daniel734@bk.ru>"]
license = "MIT"
readme = "README.md"

include = ["pyi18n_new/lib/*.py"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.9.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
