[tool.poetry]
name = "typeany"
version = "0.1.0"
description = "Preserving a cool name for Pythonn library for anytype.io. type[Any]."
authors = ["Bobronium <appkiller16@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
