# Generated by Django 3.2.12 on 2022-03-27 20:34

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('simpel_themes', '0002_auto_20220321_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltemplate',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
