
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T16:47:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6479e2604388fbabb8163d51d172ec08838b4d2",
 "version": "2022.04.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
