
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T10:57:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0ed4d2d006453f9a3b1f57a56c699c966d22b25",
 "version": "0.1.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
