[build-system]
# Minimum requirements for the build system to execute.
requires = ['Cython', 'setuptools>=48.0', 'wheel', 'pybind11>=2.2.4']

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "scm.plams.*",
    "h5py.*",
    "scipy.*",
    "noodles.*",
    "schema.*",
    "mendeleev.*",
    "pybind11.*",
    "Cython.*",
]
ignore_missing_imports = true

[tool.cibuildwheel]
build = "cp*-manylinux_x86_64"
build-verbosity = "3"
repair-wheel-command = "auditwheel -v repair -w {dest_dir} {wheel}"
manylinux-x86_64-image = "ghcr.io/nlesc-nano/manylinux2014_x86_64-qmflows"
environment = { QMFLOWS_INCLUDEDIR="", QMFLOWS_LIBDIR="", CFLAGS="-Werror", LDFLAGS="-Wl,--strip-debug" }
before-test = [
    "bash {project}/scripts/download_cp2k.sh 9.1",
    "mkdir /tmp/nanoqm",
    "cp {project}/setup.cfg /tmp/nanoqm/",
    "cp {project}/conftest.py /tmp/nanoqm/conftest.py",
    "cp -r {project}/test /tmp/nanoqm/test",
]
test-command = [
    "cd /tmp/nanoqm",
    "pytest -m 'not (slow or long)' test",
]
test-extras = ["test"]
