[tool.poetry]
name = "plexmatch"
version = "0.1.1"
description = ""
authors = [ "Cologler <skyoflw@gmail.com>" ]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Cologler/plexmatch-python"

  [tool.poetry.dependencies]
  python = "^3.8"

  [tool.poetry.dev-dependencies]
  pytest = "^7.1.1"
  pytest-cov = "^3.0.0"
  invoke = "^1.7.0"

[tool.poetry-dynamic-versioning]
enable = false

[build-system]
requires = [ "poetry-core>=1.0.0", "poetry-dynamic-versioning" ]
build-backend = "poetry.core.masonry.api"
