
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T10:55:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03d38eaf1ccfd7e8c672e9bcba8deadf21dc84a6",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
