
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T10:56:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c928282cc7e26696edab00627b288f8b421c69d",
 "version": "0.1.81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
