from irccodes import constants

BOLD = chr(constants.BOLD)
COLOR = chr(constants.COLOR)
ITALIC = chr(constants.ITALIC)
STRIKETHROUGH = chr(constants.STRIKETHROUGH)
RESET = chr(constants.RESET)
UNDERLINE = chr(constants.UNDERLINE)
MONOSPACE = chr(constants.MONOSPACE)

WHITE = str(constants.WHITE)
BLACK = str(constants.BLACK)
BLUE = str(constants.BLUE)
GREEN = str(constants.GREEN)
LIGHTRED = str(constants.LIGHTRED)
BROWN = str(constants.BROWN)
PURPLE = str(constants.PURPLE)
ORANGE = str(constants.ORANGE)
YELLOW = str(constants.YELLOW)
LIGHTGREEN = str(constants.LIGHTGREEN)
CYAN = str(constants.CYAN)
LIGHTCYAN = str(constants.LIGHTCYAN)
LIGHTBLUE = str(constants.LIGHTBLUE)
PINK = str(constants.PINK)
GREY = str(constants.GREY)
LIGHTGRAY = str(constants.LIGHTGRAY)
