# Copyright (c) 2022 mudpy authors. Permission to use, copy,
# modify, and distribute this software is granted under terms
# provided in the LICENSE file distributed with this software.

[build-system]
requires = ["pbr>=5.8.0", "setuptools>=36.6.0"]
build-backend = "pbr.build"
