[tool.poetry]
name = "euler-math"
version = "0.4.0"
description = "Utilities for Project Euler"
authors = ["David Carlson <mndrake22@mac.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
gmpy2 = "^2.1.2"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
