[tool.poetry]
name = "raptor_functions"
version = "0.2.36"
description = "raptor functions"
repository = "https://github.com/Bryant-Dental/raptor_functions.git"
authors = ["Daniel Fiuza, Ibrahim Animashaun"]



[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
