
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-17T02:32:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c4fae6a91eba8262de2c1a9665055edcd5605f3",
 "version": "0.9.dev2216"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
