
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T17:59:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "18b711bcf52009bc33c28c9f71342b2fac7b03aa",
 "version": "5.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
