
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-18T08:39:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "65a8495e85936e5aa151c4c04df5563b4fc7af24",
 "version": "v0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
