[tool.poetry]
name = "sb-portal-gun"
version = "0.1.0"
description = ""
authors = ["Siddhartha Basu <basu.siddhartha@outlook.com>"]
readme = "README.md"

[tool.poetry.scripts]
sb-portal-gun = "sb_portal_gun.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.4.1"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
black = {version = "^22.3.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
