[tool.poetry]
name = "understory-auth"
version = "0.0.27"
description = "Authentication in the understory"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "AGPL-3.0-or-later"
packages = [{include = "understory"}]

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0.0"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name = "main"
url = "http://localhost:8080/_pypi"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
