[tool.poetry]
name = "aiohttp-boilerplate"
version = "0.2.6"
description = ""
authors = ["Vladyslav Tarasenko <vladka@webdevelop.pro>", "Artem Tiumentcev <artem@webdevelop.pro>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7"
aiohttp = "3.8.1"
asyncpg = "0.25.0"
marshmallow = "3.15.0"
ujson = "5.2.0"
uvloop = "0.14.0"
PyJWT = "2.3.0"
aiocache = "0.11.1"
python-json-logger = "2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
