[tool.poetry]
name = "trends"
version = "0.3.0"
description = "Generate and study quasi-monotonic sequences."
authors = ["Jeffrey S. Haemer <jeffrey.haemer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8-bugbear = "^22.3.23"
flake8-bandit = "^3.0.0"
flake8-docstrings = "^1.6.0"
isort = "^5.10.1"
mutmut = "^2.4.0"
mypy = "^0.942"
pre-commit = "^2.18.1"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-random-order = "^1.0.4"
pyupgrade = "^2.32.0"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
