# Generated by Django 3.2.12 on 2022-03-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_themes', '0003_alter_modeltemplate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshoot',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_screenshoots', to='simpel_themes.modeltemplate', verbose_name='template'),
        ),
    ]
