# Version file autogenerated by the build process
version = '0.10.0-beta4'
build = 1080
vcs_info = 'Git SHA1 8d4176e5 committed on 2022-04-20'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.10.0-beta4"\nKSCONF_BUILD="1080"\nKSCONF_VCS_INFO="Git SHA1 8d4176e5 committed on 2022-04-20"')
