# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:37
from django.db import migrations, models
import django.db.models.deletion
import shatail.blocks
import shatail.fields
import shatail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("shatailcore", "0029_unicode_slugfield_dj19"),
        ("tests", "0008_inlinestreampage_inlinestreampagesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultStreamPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shatailcore.Page",
                    ),
                ),
                (
                    "body",
                    shatail.fields.StreamField(
                        (
                            ("text", shatail.blocks.CharBlock()),
                            ("rich_text", shatail.blocks.RichTextBlock()),
                            ("image", shatail.images.blocks.ImageChooserBlock()),
                        ),
                        default="",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("shatailcore.page",),
        ),
    ]
