# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:57
from django.db import migrations
import shatail.test.testapp.models
import shatail.blocks
import shatail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0012_panelsettings_tabbedsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.test.testapp.models.ExtendedImageChooserBlock()),
                ]
            ),
        ),
    ]
