# Generated by Django 2.1.7 on 2019-03-28 02:30

from django.db import migrations, models
import shatail.blocks
import shatail.fields
import shatail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0057_customdocumentwithauthor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockCountsStreamModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    shatail.fields.StreamField(
                        [
                            ("text", shatail.blocks.CharBlock()),
                            ("rich_text", shatail.blocks.RichTextBlock()),
                            ("image", shatail.images.blocks.ImageChooserBlock()),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinMaxCountStreamModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    shatail.fields.StreamField(
                        [
                            ("text", shatail.blocks.CharBlock()),
                            ("rich_text", shatail.blocks.RichTextBlock()),
                            ("image", shatail.images.blocks.ImageChooserBlock()),
                        ]
                    ),
                ),
            ],
        ),
    ]
