# Generated by Django 4.0.3 on 2022-03-18 06:36

from django.db import migrations
import shatail.blocks
import shatail.contrib.table_block.blocks
import shatail.fields
import shatail.images.blocks
import shatail.test.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0061_tag_fk_for_django_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addedstreamfieldwithemptylistdefaultpage",
            name="body",
            field=shatail.fields.StreamField(
                [("title", shatail.blocks.CharBlock())],
                default=[],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="addedstreamfieldwithemptystringdefaultpage",
            name="body",
            field=shatail.fields.StreamField(
                [("title", shatail.blocks.CharBlock())],
                default="",
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="addedstreamfieldwithoutdefaultpage",
            name="body",
            field=shatail.fields.StreamField(
                [("title", shatail.blocks.CharBlock())], use_json_field=False
            ),
        ),
        migrations.AlterField(
            model_name="blockcountsstreammodel",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="customrichblockfieldpage",
            name="body",
            field=shatail.fields.StreamField(
                [("rich_text", shatail.blocks.RichTextBlock(editor="custom"))],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="deadlystreampage",
            name="body",
            field=shatail.fields.StreamField(
                [("title", shatail.test.testapp.models.DeadlyCharBlock())],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="defaultrichblockfieldpage",
            name="body",
            field=shatail.fields.StreamField(
                [("rich_text", shatail.blocks.RichTextBlock())], use_json_field=False
            ),
        ),
        migrations.AlterField(
            model_name="defaultstreampage",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.images.blocks.ImageChooserBlock()),
                ],
                default="",
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="inlinestreampagesection",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="minmaxcountstreammodel",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="streammodel",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=shatail.fields.StreamField(
                [
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.test.testapp.models.ExtendedImageChooserBlock()),
                    (
                        "product",
                        shatail.blocks.StructBlock(
                            [
                                ("name", shatail.blocks.CharBlock()),
                                ("price", shatail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    ("raw_html", shatail.blocks.RawHTMLBlock()),
                    (
                        "books",
                        shatail.blocks.StreamBlock(
                            [
                                ("title", shatail.blocks.CharBlock()),
                                ("author", shatail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=False,
            ),
        ),
        migrations.AlterField(
            model_name="tableblockstreampage",
            name="table",
            field=shatail.fields.StreamField(
                [("table", shatail.contrib.table_block.blocks.TableBlock())],
                use_json_field=False,
            ),
        ),
    ]
