class ConfigurationError( Exception ) : ...


class StaticAttributesIsRequired( ConfigurationError ) : ... 
class AttributeIsRequired       ( ConfigurationError ) : ... 
class InvalideValueType         ( ConfigurationError ) : ...