[tool.poetry]
name = "dailymotion_api"
version = "0.0.6"
description = "Dailymotion api"
authors = [
    "Vladimir Emil Rueda G贸mez <vladimir.rueda@udea.edu.co>",
    "Vladimir Emil Rueda G贸mez <vladimir.rueda@udea.edu.co>"
    ]
maintainers = [
    "Vladimir Emil Rueda G贸mez <vladimir.rueda@udea.edu.co>",
    "Vladimir Emil Rueda G贸mez <vladimir.rueda@udea.edu.co>"
    ]
readme = "README.rst"
homepage = "https://pypi.org/project/dailymotion_api/"
keywords = [
    "Complex Systems",
    "Computation",
    "Epidemiology",
    "Nonlinear dynamics",
    "Agent Based Models"
    ]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Education",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries"
    ]
license = "GPL-3.0-only"
[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.74.1"
uvicorn = "^0.17.5"
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
