[tool.poetry]
name = "hata_init"
version = "0.1.0"
description = "A cli plugin for hata which allows you to make bots fast"
authors = ["WizzyGeek <51919967+WizzyGeek@users.noreply.github.com>"]
license = "MIT"
packages = [
    {include = "hata"}
]

[tool.poetry.dependencies]
python = "^3.6"
hata = "^1.2.8"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
