
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T13:25:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "407bc2b92449416d35e0d2a9da9af86b44362637",
 "version": "2656"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
