[package]
name = "vegafusion-core"
version = "0.3.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[features]
tonic_support = [ "tonic", "tonic-build",]

[dependencies]
thiserror = "^1.0.29"
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
itertools = "0.10.1"
lazy_static = "^1.4.0"
regex = "^1.5.4"
serde_json = "1.0.79"
ordered-float = "^2.8.0"
petgraph = "0.6.0"
deterministic-hash = "1.0.1"
chrono = "0.4.19"

[build-dependencies]
prost-build = "0.9.0"

[dependencies.arrow]
version = "11.0.0"
default_features = false
features = [ "ipc",]

[dependencies.datafusion-common]
git = "https://github.com/apache/arrow-datafusion.git"
rev = "4c2320e783ddf54086d345b8d4e3d8a70611aab4"

[dependencies.pyo3]
version = "0.16.1"
optional = true

[dependencies.serde]
version = "1.0.136"
features = [ "derive",]

[dependencies.tonic]
version = "0.6.1"
optional = true

[build-dependencies.tonic-build]
version = "0.6.2"
optional = true
