[tool.poetry]
name = "simpleini"
version = "0.1.2"
description = "Simple use ini files"
authors = ["to101 <to101kv@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
APPLICATION-NAME = '__init__:main'