
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T14:20:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7c75f06a638fac818bebe7e73e8908382ae2413",
 "version": "2651"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
