[tool.poetry]
name = "japre"
version = "0.1.4"
description = "Custom pretokenizers for Japanese language models"
authors = ["Kaito Sugimoto <kaito_sugimoto@is.s.u-tokyo.ac.jp>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Alab-NII/japanese_pretokenizers"
repository = "https://github.com/Alab-NII/japanese_pretokenizers"

[tool.poetry.dependencies]
python = ">=3.7"
fugashi = ">=1.1.0"
ipadic = ">=1.0.0"
pytextspan = ">=0.5.0"
tokenizers = ">=0.10.0"
flake8 = ">=4.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
