
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-24T09:52:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e160029e7f3070875307c3520e1a683c9b274d48",
 "version": "2.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
