# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apeman_model_client import apemanModelClient_pb2 as apeman__model__client_dot_apemanModelClient__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ApemanModelClientStub(object):
    """definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Report = channel.unary_unary(
                '/ApemanModelClient/Report',
                request_serializer=apeman__model__client_dot_apemanModelClient__pb2.TaskStatusReportRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetModelEndpoint = channel.unary_unary(
                '/ApemanModelClient/GetModelEndpoint',
                request_serializer=apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointRequest.SerializeToString,
                response_deserializer=apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointResponse.FromString,
                )


class ApemanModelClientServicer(object):
    """definition.
    """

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelEndpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApemanModelClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=apeman__model__client_dot_apemanModelClient__pb2.TaskStatusReportRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetModelEndpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelEndpoint,
                    request_deserializer=apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointRequest.FromString,
                    response_serializer=apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ApemanModelClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ApemanModelClient(object):
    """definition.
    """

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ApemanModelClient/Report',
            apeman__model__client_dot_apemanModelClient__pb2.TaskStatusReportRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelEndpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ApemanModelClient/GetModelEndpoint',
            apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointRequest.SerializeToString,
            apeman__model__client_dot_apemanModelClient__pb2.GetModelEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
