# Generated by Django 3.0.13 on 2022-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='Executed'),
        ),
        migrations.AddField(
            model_name='callback',
            name='outstanding',
            field=models.BooleanField(default=False, verbose_name='Outstanding'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
