
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T16:16:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "67d7284ad54ebdc5933dd6f30a1ea4a79ce4aa75",
 "version": "1.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
