
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T14:55:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0df35c7bce24d92bb01cce5d8ae0b3e2fa6d2e41",
 "version": "1.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
