
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T20:59:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "70afd4fcb9a834cf4d1a3917cc6028ae326ad29e",
 "version": "2022.04.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
