"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeTicketingClient
from MergeTicketingClient.model.categories_enum import CategoriesEnum
globals()['CategoriesEnum'] = CategoriesEnum
from MergeTicketingClient.model.account_integration import AccountIntegration


class TestAccountIntegration(unittest.TestCase):
    """AccountIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountIntegration(self):
        """Test AccountIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
