"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeTicketingClient
from MergeTicketingClient.model.attachment_request import AttachmentRequest
globals()['AttachmentRequest'] = AttachmentRequest
from MergeTicketingClient.model.ticketing_attachment_endpoint_request import TicketingAttachmentEndpointRequest


class TestTicketingAttachmentEndpointRequest(unittest.TestCase):
    """TicketingAttachmentEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketingAttachmentEndpointRequest(self):
        """Test TicketingAttachmentEndpointRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TicketingAttachmentEndpointRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
