"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeTicketingClient
from MergeTicketingClient.model.categories_enum import CategoriesEnum
from MergeTicketingClient.model.model_operation import ModelOperation
globals()['CategoriesEnum'] = CategoriesEnum
globals()['ModelOperation'] = ModelOperation
from MergeTicketingClient.model.account_details_and_actions_integration import AccountDetailsAndActionsIntegration


class TestAccountDetailsAndActionsIntegration(unittest.TestCase):
    """AccountDetailsAndActionsIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountDetailsAndActionsIntegration(self):
        """Test AccountDetailsAndActionsIntegration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountDetailsAndActionsIntegration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
