"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeTicketingClient
from MergeTicketingClient.model.ticket import Ticket
globals()['Ticket'] = Ticket
from MergeTicketingClient.model.paginated_ticket_list import PaginatedTicketList


class TestPaginatedTicketList(unittest.TestCase):
    """PaginatedTicketList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTicketList(self):
        """Test PaginatedTicketList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTicketList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
