"""
    Merge Ticketing API

    The unified API for building rich integrations with multiple Ticketing platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeTicketingClient
from MergeTicketingClient.model.attachment import Attachment
from MergeTicketingClient.model.debug_mode_log import DebugModeLog
from MergeTicketingClient.model.error_validation_problem import ErrorValidationProblem
from MergeTicketingClient.model.warning_validation_problem import WarningValidationProblem
globals()['Attachment'] = Attachment
globals()['DebugModeLog'] = DebugModeLog
globals()['ErrorValidationProblem'] = ErrorValidationProblem
globals()['WarningValidationProblem'] = WarningValidationProblem
from MergeTicketingClient.model.ticketing_attachment_response import TicketingAttachmentResponse


class TestTicketingAttachmentResponse(unittest.TestCase):
    """TicketingAttachmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTicketingAttachmentResponse(self):
        """Test TicketingAttachmentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TicketingAttachmentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
