
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T14:30:18+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a0e874b2497e74a7f94967d28439037f72fc362",
 "version": "1.91"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
