
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-18T13:45:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd61eaa2651523da9b769e7658fa1cc45dc7b5cd",
 "version": "5.8.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
