# flake8: noqa

"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from MergeCRMClient.api_client import ApiClient

# import Configuration
from MergeCRMClient.configuration import Configuration

# import exceptions
from MergeCRMClient.exceptions import OpenApiException
from MergeCRMClient.exceptions import ApiAttributeError
from MergeCRMClient.exceptions import ApiTypeError
from MergeCRMClient.exceptions import ApiValueError
from MergeCRMClient.exceptions import ApiKeyError
from MergeCRMClient.exceptions import ApiException
