
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T15:34:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8837cdaf536a435c1aa96dd726c3c956ac1147ba",
 "version": "0.7.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
