[tool.poetry]
name = "shownode"
version = "0.1.0"
description = "Connect to docker containers with open vnc ports"
authors = ["dskard"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.1"
pdbpp = "^0.10.3"

[tool.poetry.scripts]
shownode = "shownode.shownode:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
