[tool.poetry]
name = "slskit"
version = "2022.4.0"
authors = ["Gediminas Zlatkus <gediminas.zlatkus@gmail.com>"]
description = "Tools for checking Salt state validity"
readme = "README.md"
homepage = "https://github.com/gediminasz/slskit"
repository = "https://github.com/gediminasz/slskit"
keywords = ["salt", "saltstack", "sls"]
classifiers = ["Topic :: Software Development :: Quality Assurance"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.2"
colorlog = "^6.6.0"
funcy = "^1.17"
# TODO remove Jinja2 line when this fix is released https://github.com/saltstack/salt/issues/61848
Jinja2 = "<3.1"
jsonschema = "^4.4.0"
salt = ">=3001.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
GitPython = "^3.1.27"
mypy = "^0.942"
pylint = "^2.13.7"
pytest = "^7.1.1"
pytest-snapshot = "^0.8.1"
types-PyYAML = "^6.0.7"

[tool.poetry.scripts]
slskit = 'slskit:run_module'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
