from enum import Enum


class SensorType(str, Enum):
    PERCENTAGE = 'PERCENTAGE',
    TEMPERATURE = 'TEMPERATURE',
    COUNT = 'COUNT',
    FLOAT = 'FLOAT',
    DISTANCE = 'DISTANCE',
    TIMESTAMP = 'TIMESTAMP',
    IDENTIFIER = 'IDENTIFIER',
    HUMIDITY = 'HUMIDITY',
    CONCENTRATION = 'CONCENTRATION',
    LASER_POWER = 'LASER_POWER',
    BOOLEAN = 'BOOLEAN',
    VOLTAGE = 'VOLTAGE',
    PRESSURE = 'PRESSURE',
    STRING = 'STRING',
    FLOW = 'FLOW',
    WEIGHT = 'WEIGHT',
    AMPERE = 'AMPERE'

