[tool.irt.dependencies]
core-component = "https://github.com/inmanta/inmanta-core"

[tool.irt.documentation]
documentation_base_repo = "https://github.com/inmanta/inmanta-core.git"
documentation_repo = "https://github.com/inmanta/inmanta.git"

[tool.irt.module_set]
path = "sets/public.yml"

[tool.irt.build.rpm]
centos_versions = [ 8,]
python_version = "python3.9"

[tool.irt.publish.python]
public = true

[tool.irt.publish.rpm]
rpm_repo_name_prefix = "inmanta/oss"

[tool.irt.dependencies.extensions]
inmanta-ui = "https://github.com/inmanta/inmanta-ui"

[tool.irt.documentation.publish]
dev_release_path = "/srv/www/docs/community/{version}.dev"
stable_release_path = "/srv/www/docs/community/{version}"
post_publish_hook_remote = "~/post_publish_hook.py"

[tool.irt.additional-lock-files.inmanta-core]
repo = "https://github.com/inmanta/inmanta-core"
files = [ "requirements.txt", "requirements.setup.txt",]

[tool.irt.build.rpm.enable_repo]
el8 = []

[tool.irt.dependencies.npm.inmanta-dashboard]
repo = "https://github.com/inmanta/inmanta-dashboard"
version = "==3.8.1"

[tool.irt.dependencies.npm.web-console]
repo = "https://github.com/inmanta/web-console"
version = "==1.10.0"
