VERSION_YEAR = 2022
VERSION_MONTH = int('04')
VERSION_DAY = int('17')
VERSION_HOUR = int('04')
VERSION_MINUTE = int('51')
MAJOR_VERSION = 0
MINOR_VERSION = 4
PATCH_VERSION = 202204170451
version_date = '2022/04/17 04:51'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
