
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-23T21:57:02+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "f638c1154e0598d893d601aa0c63c4c7ff68ff7f",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
