
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T10:10:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6385303bf6aeab9dd1f7aad8926232e07c33c333",
 "version": "2659"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
