[tool.poetry]
name = "csnake"
version = "0.3.5"
description = "C code generation helper package."
authors = ["Andrej Radović <r.andrej@gmail.com>"]
license = "MIT"
readme = "README.rst"
repository = "https://gitlab.com/andrejr/csnake"
documentation = "https://andrejr.gitlab.io/csnake/"
keywords = ["codegen", "c", "embedded"]
classifiers = [
    # Trove classifiers
    # Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: Software Development :: Pre-processors",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE.md",
]

packages = [
    {include = "csnake"},
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
# optionals
numpy = {version = ">=1.17", optional = true}
sympy = {version = ">=1.4", optional = true}
pillow = {version = ">=6.1", optional = true}

[tool.poetry.extras]
numpy = ["numpy"]
sympy = ["sympy"]
pillow = ["pillow"]

[tool.poetry.dev-dependencies]
Sphinx = "^4.1"
black = "^22.3"
coverage = "^5.5"
flake8 = "^3.9"
flake8-bugbear = "^21.4"
flake8-builtins = "^1.5"
flake8-comprehensions = "^3.6"
flake8-polyfill = "^1.0"
flake8-rst-docstrings = "^0.2"
ipython = "^7.27"
jedi = "^0.18"
mypy = "^0.910"
neovim = "^0.3"
pre-commit = "^2.15"
profilehooks = "^1.12"
pytest = "^6.2"
pytest-cov = "^2.12"
pytest-html = "^3.1"
reorder-python-imports = "^2.6"
rope = "^0.19"
sphinx-argparse = "^0.3"
sphinx-autodoc-typehints = "^1.12"
numpy = "^1.21.2"
sympy = "^1.8"
Pillow = "^8.3.2"
readme-renderer = "^34.0"


[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
