
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T19:17:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c7a2e61b710b10f356263759ae999218655f400",
 "version": "3.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
