name = "Español (España)"
author = "aveeryy"

[main]
exit_msg = "Saliendo..."
unlocking = "Desbloqueando la descarga de %s"

[args]
added_arg = "Añadido argumento \"%s\" de %s"

[args.except]
argument_variable_empty = "El campo \"variable\" del argumento %s está vacio, por favor informa (o arregla) esto"

[args.help]
accounts_dir = "Directorio alternativo para archivos de cuentas"
binaries_dir = "Directorio alternativo para binarios de ffmpeg"
config_file = "Dirección alternativa para el archivo de configuración"
download_dir_generic = "Directorio de descarga para contenido genérico"
download_dir_series = "Directorio de descarga para las series"
download_dir_movies = "Directorio de descarga para las películas"
dump = "Volcar información a un archivo"
email = "Email de la cuenta de %s"
exit_after_dump = "Salir tras volcar la información"
extended_help = "Muestra las opciones de los argumentos"
filters = "Filtros de extracción y descarga"
format_episode = "Formato para el nombre de archivo de los episodios"
format_generic = "Formato para el nombre de archivo de contenido genérico"
format_movie = "Formato para el nombre de archivo de las películas"
format_search = "Formato para los resultados de búsqueda"
help = "Muestra la ayuda"
install_languages = "Instala los idiomas especificados"
installed_languages = "Muestra una lista de los idiomas instalados"
language = "Utiliza el idioma especificado"
language_dir = "Directorio alternativo para archivos de idioma"
log_dir = "Directorio alternativo para archivos de registro"
log_file = "Dirección alternativa para el registro de descargas"
max_results = "Máximo absoluto de resultados de búsqueda"
max_results_per_extractor = "Resultados de búsqueda por extractor"
max_results_per_type = "Resultados de búsqueda por tipo de contenido"
mode = "Modo de ejecución"
pass = "Contraseña de la cuenta de %s"
redownload = "Permite descargar contenido ya descargado previamente"
remove_chars = "Quita carácteres inválidos de Windows en los nombres de archivo en vez de reemplazarlos"
resolution = "Resolución de video preferida"
results_trim = "Reduce los nombres de los resultados de búsqueda"
temp_dir = "Directorio alternativo para archivos temporales"
update = "Actualiza al último lanzamiento estable"
update_check = "Comprueba si hay actualizaciones al iniciar"
update_git = 'Actualiza al último lanzamiento git'
update_languages = "Actualiza los idiomas descargados"
url = "Enlaces"
verbose = "Nivel de detallado de la salida"
verbose_log = "Nivel de detallado de los registros"

[args.groups]
general = "Opciones generales"
download = "Opciones de descarga"
extractor = "Opciones de %s"
debug = "Opciones de depuración"
search = "Opciones de búsqueda"

[polarity]
all_tasks_finished = "Todas las tareas han finalizado en %s"
changed_index = "Cambiado índice a %s"
config_path = "Configuración cargada desde %s"
created_filter = "Creado objeto %s con los parámetros %s y el filtro %s"
deleting_log = "Nada que hacer, borrando registro"
dump_options = "las opciones"
dumped_to = "Volcadas %s en: %s"
filter_processing = "Procesando los filtros"
finished_download = "Finalizadas las tareas de descarga"
finished_extraction = "Finalizadas las tareas de extracción"
installed_languages = "Idiomas instalados:"
language_format = "%s [%s] por %s"
log_path = "Escribiendo registro en: %s"
not_a_content_id = '"%s" no es un identificador de contenido'
no_space_left = "No queda espacio disponible en el dispositivo, saliendo..."
python_version = "Python %s | %s"
requesting = "Solicitando: %s"
search_no_results = "No se han encontrado resultados con el término: %s"
search_term = "Término de búsqueda: "
search_usage = "polarity --mode search [OPCIONES] TÉRMINO_DE_BÚSQUEDA"
unknown_channel = "ID del canal de televisión desconocido"
unsupported_python = "Versión de Python no soportada (%s), actualiza a Python 3.7 o superior"
update_available = "La versión %s está disponible"
usage = "polarity [OPCIONES] URL [URL...]"
use_help = "Usa --help para mostrar todas las opciones disponibles"
use = 'Uso: '
using_version = "Polarity %s"

[polarity.except]
invalid_http_method = "Método HTTP inválido: %s"
missing_ffmpeg = "ffmpeg no está instalado o no está en PATH"
verbose_error = "Nivel de detallado invalido: %s"
verbose_log_error = "Nivel de detallado de registros invalido: %s"

[dl]
cannot_download_content = "No se puede descargar %s \"%s\": %s"
content_id = "el identificador de contenido"
download_successful = "Se ha descargado %s \"%s\""
downloading_content = "Descargando %s \"%s\""
no_extractor = "Saltando %s \"%s\". No hay un extractor compatible"
no_redownload = "Saltando %s \"%s\". Ya se ha descargado previamente"
url = "la URL"

[penguin]
assisting = "Asistiendo al hilo de descarga %s con %s"
current_pool = "Pool actual: %s"
download_locked = "No se puede descargar \"%s\", bloqueado por otro descargador"
ffmpeg_remux_failed = "El proceso de ffmpeg ha crasheado, abortando, por favor crea una \"issue\" en GitHub con el siguiente archivo adjunto: %s"
key_download = "Descargando la llave de desencriptado del segmento %s"
output_file_broken = "No se ha podido cargar el archivo de datos de descarga, recreando..."
processing_stream = "Procesando el stream %s"
resuming = "Resumiendo la descarga de %s..."
segment_downloaded = "Se ha descargado con éxito el segmento %s"
segment_retry = "La descarga del segmento %s ha fallado, reintentando..."
segment_skip = "Saltando el segmento %s"
segment_start = "Descargando el segmento %s"
stream_protocol = "Usando el protocolo %s para el stream %s"
thread_started = "Se ha iniciado el hilo \"%s\""
threads_started = "Iniciando %d hilos de descarga"

[penguin.args]
keep_logs = "Copia los registros de descarga junto al archivo final"
tag_output = "Añade la versión de Polarity al archivo final"
threads = "Número de hilos por descarga"

[penguin.except]
download_fail = "No se ha podido descargar el segmento %s: %s"

[penguin.protocols]
getting_playlist = "Analizando playlist"
getting_stream = "Analizando stream"
multiple_video_bitrates = "Múltiples pistas de audio con la misma resolución detectadas"
picking_best_stream_0 = "Seleccionando el stream de video con mayor resolución"
picking_best_stream_1 = "Seleccionando el stream de video con mayor bitrate"
picking_best_stream_2 = "Seleccionando el mejor stream"
selected_stream = "Stream seleccionado: %s"

[extractor]
filter_check_fail = "No cumple con los filtros"
generic_error = "¡Ha ocurrido un error! Por favor informa de esto en GitHub: %s"
get_all_seasons = "Obteniendo información de todas las temporadas"
get_media_info = "Obteniendo información %s \"%s\" (%s)"
login_expired = "¡El inicio de sesión ha expirado!"
login_failure = "Error al iniciar sesión. Error: %s"
login_loggedas = "Sesión iniciada como %s"
login_success = "Inicio de sesión exitoso"
search_no_results = "No ha habido resultados en la categoría %s con el término %s"
skip_dl_premium = "Contenido premium o no en tu región"
waiting_for_login = "Esperando a que inicies sesión"

[extractor.base]
check_failed = "La comprobación de la característica %s ha fallado, no se cumplen las siguientes condiciones: %s"
email_prompt = "Email/Usuario: "
password_prompt = "Contraseña: "
using_filters = "Usando filtros, el total en la barra de progreso va a ser impreciso"

[extractor.base.except]
failed_load_cookiejar = "No se ha podido cargar la cookiejar: %s"
no_cookiejar = "El extractor no tiene una cookiejar"

[extractor.check]
invalid_extractor = "El extractor de contenido %s no es válido"

[extractor.check.features]
base = "funcionalidad base"
login = "inicio de sesión"
search = "búsqueda"
livetv = "tv en directo"

[extractor.except]
argument_missing = "El parámetro %s es requerido"
cannot_identify_url = "No se ha podido identificar el enlace"
no_id = "No se ha introducido un id"
no_url = "No se ha introducido una URL"

[types]
series = "la serie"
season = "la temporada"
episode = "el episodio"
movie = "la película"
content = "el contenido"
contentcontainer = "el contentedor de contenido"

[types.alt]
series = "de la serie"
season = "de la temporada"
episode = "del episodio"
movie = "de la película"
content = "del contenido"
contentcontainer = "del contenedor de contenido"

[update]
downloading_git = "Descargando el último lanzamiento git"
downloading_release = "Descargando el último lanzamiento estable"
downloading_native = "Descargando el último binario nativo"
new_release = "Nuevo lanzamiento disponible: %s"

[update.except]
unsupported_native = "Actualizar binarios nativos no está implementado"

[atresplayer]
no_content_in_season = "No hay episodios en %s (%s)"
no_seasons = "El contenido no tiene temporadas"

[atresplayer.except]
invalid_codec = "El códec especificado en los ajustes es inválido."

[atresplayer.args]
codec = "Preferencia del códec"

[crunchyroll]
bearer_fetch = "Obteniendo token Bearer"
bearer_fetch_fail = "Ha fallado la obtención del token bearer"
cms_fetch = "Obteniendo políticas CMS"
cms_fetch_fail = "Ha fallado la obtención de políticas CMS"
unwanted_season = "Saltando la temporada %s, doblaje filtrado"
using_method = "Usando el método \"%s\""

[crunchyroll.args]
subs = "Idiomas de los subtítulos a descargar"
dubs = "Idiomas de los doblajes a descargar"
meta = "Idioma de los metadatos"
hard = "Idioma de los subtítulos incrustados"

[pokemontv]
get_channel_info = "Obteniendo canales"
get_region_info = "Obteniendo región"

[limelight]
available_formats = "Formatos disponibles: %s"
set_wanted_format = "Se ha seleccionado el stream con el formato %s como preferido"

[limelight.args]
format = "Formato de stream a descargar"

[limelight.except]
invalid_id = "Identificador de formato inválido: %s"
unsupported_rtmp = "Los streams RTMP no están soportados"
