[tool.pdm]
build = "build.py"
source-includes = [
    "tests",
    "LICENSE",
    "README.md",
]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.0.1",
    "cibuildwheel>=2.3.1",
    "pre-commit>=2.17.0",
    "pytest-benchmark>=3.4.1",
]

[tool.pdm.scripts]
lint = "pre-commit"

[tool.black]
addopts = "--fast"
exclude = "(\n  /(\n      \\.eggs         # exclude a few common directories in the\n    | \\.git          # root of the project\n    | \\.hg\n    | \\.mypy_cache\n    | \\.tox\n    | \\.venv\n    | _build\n    | buck-out\n    | build\n    | dist\n  )/\n  | manage.py           # also separately exclude a file named foo.py in\n)\n"
line-length = 119
target_version = [
    "py37",
]

[tool.isort]
known_third_party = [
    "pytest",
]
line_length = 119
profile = "black"
skip_gitignore = "True"
force_single_line = "True"

[tool.cibuildwheel]
build = "*"

[build-system]
requires = [
    "pdm-pep517",
    "setuptools>=42",
    "wheel",
]
build-backend = "pdm.pep517.api"

[project]
name = "yascc"
version = "0.3.5"
description = "Yet another string case converter"
readme = "README.md"
authors = [
    { name = "urm8", email = "arctgisnil@gmail.com" },
]
dependencies = []
requires-python = ">=3.7"
classifiers = [
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[project.license]
text = "DTFYW"

[project.urls]
Homepage = "https://github.com/urm8/yascc"
Repository = "https://github.com/urm8/yascc"

[project.optional-dependencies]
