
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-16T16:33:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d00f120da3e847d60255354216dac0531c3824df",
 "version": "0.0.74.post0.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
