
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T22:27:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "87433a26efc355cc60c85131e8ebd73c1fafd74a",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
