[tool.poetry]
name = "cognite-extractor-manager"
version = "0.5.0"
description = "A project manager for Python based extractors"
authors = ["Mathias Lohne <mathias.lohne@cognite.com>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include="cognite", from="." },
]

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files
known_third_party = ["requests", "termcolor", "toml"]

[tool.poetry.dependencies]
python = "^3.7.0"
termcolor = "^1.1.0"
requests = "^2.26.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
twine = "^3.8.0"
flake8 = "*"
pre-commit = "^2.2.0"

[tool.poetry.scripts]
cogex = "cognite.extractorutils.cogex.__main__:main"

[tool.cogex]
docker-tags = ["cogex-test:latest"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
