
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T16:03:18+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "827ff9109476b0625c33259c9fe827348a5ff9bd",
 "version": "2.9.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
