# Setuptools

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
	'setuptools >= 60.6.0',
	'setuptools-scm[toml] >= 6.4.2',
	'wheel >= 0.37.1',
]

[tool.setuptools_scm]
version_scheme = 'post-release'
write_to = 'no_vtf/_version.py'

# Other

[tool.black]
color = true
extend-exclude = '''
	/generated/
'''
fast = true
line-length = 100
quiet = true
target-version = ['py310']
