name: CI

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: pip3 install build
      - run: python3 -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
          if-no-files-found: error
          retention-days: 5
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "openvpn_auth_azure_ad"
        use-pylint: false
        use-isort: false
        use-mypy: false

  publish:
    name: Publish package
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

  release:
    name: Create release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - publish
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') }}
          body: |-
            # CHANGELOG
            * https://github.com/jkroepke/openvpn-auth-azure-ad/blob/${{ github.ref_name }}/CHANGELOG.md
            ## DockerHub
            * https://hub.docker.com/r/jkroepke/openvpn-auth-azure-ad/tags?name=${{ github.ref_name }}
