[tool.poetry]
name = "tinkerbox"
version = "0.1.0"
description = "tidbits to play around with"
authors = ["Subodh Lamichhane"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
