[tool.poetry]
name = "pytocode"
version = "0.1.1"
description = ""
authors = ["Kyle Oliver <56kyleoliver@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
