
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T14:15:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "411a6f53f00ee04db1fa4d9c55a0d0da189f4396",
 "version": "0.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
