
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T11:00:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6e79acd420a663bf03103dfffd19b80804372cc",
 "version": "0.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
