[tool.poetry]
name = "mysqler"
version = "0.1.0"
description = "mysql for human."
authors = ["tuna2134 <masato.04.11.2007@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.10"
aiomysql = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
