
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T10:56:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fe007f7672ff0b9c7f8121de22625e3cd75b610",
 "version": "0.1.136"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
