from typing import Any

class Response:
    body: str
    status: int

    def __init__(self, body: str, status: int): ...

class Server:
    def __init__(self): ...
    def add_route(self, path: str, route: type, **kwargs: Any): ...
    async def start(self, host: str): ...

class Route:
    async def setup(self): ...
    async def get(self, *args): ...
    async def post(self, *args): ...
    async def put(self, *args): ...
    async def delete(self, *args): ...
    async def patch(self, *args): ...
    async def options(self, *args): ...
    async def head(self, *args): ...
