ACCESS_TOKEN_STORAGE_KEY = "smsdrop_bearer_token"
BASE_URL = "https://smsdrop.edevtecapps.com"
USER_PATH = "/api/users/me"
LOGIN_PATH = "/api/auth/login"
CAMPAIGN_BASE_PATH = "/api/campaigns/"
CAMPAIGN_RETRY_PATH = "/api/campaigns/retry"
SUBSCRIPTION_PATH = "/api/subscriptions/"
