from typing import Any

HAILORT_SUPPORTED_VERSIONS: Any

class HailoRT:
    def __init__(self, model_config) -> None: ...
    def load_engine(self): ...
    def activate_pipeline(self) -> None: ...
    def close_pipeline(self): ...
    configured_network: Any
    activated_network: Any
    def activate_network(self): ...
    def set_input(self, image) -> None: ...
    input_data: Any
    def forward(self): ...
    def deactivate_network(self, *args) -> None: ...
    def stop(self, *args) -> None: ...
