from typing import Any

class OpenCV:
    net: Any
    layer_names: Any
    def __init__(self, model_config) -> None: ...
    def forward(self): ...
    def set_input(self, input) -> None: ...
    def set_backend(self, backend) -> None: ...
    def set_accelerator(self, target) -> None: ...
    def set_layer_names(self) -> None: ...
