
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T16:38:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "29d45b7a88f6473e44d700f641db11a387850075",
 "version": "v0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
