[tool.poetry]
name = "siteup"
version = "0.1.0"
description = "cli tool to check online status of websites"
authors = ["BrianLusina <12752833+BrianLusina@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
pre-commit = "^2.18.1"
pip-licenses = "^3.5.3"
twine = "^4.0.0"
build = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
