[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "cogent3"
author = "Gavin Huttley"
author-email = "Gavin.Huttley@anu.edu.au"
home-page = "https://cogent3.org"
keywords = "biology, genomics, statistics, phylogeny, evolution, bioinformatics"
description-file = "README.md"
license = "BSD-3"
requires-python = ">=3.7,<3.11"
requires = ["chardet",
        "numpy",
        "numba>0.48.0;python_version<'3.9'",
        "numba>0.53; python_version>='3.9'",
        "numba>0.54; python_version>='3.10'",
        "scitrack",
        "tqdm",
        "tinydb"]
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ]

[tool.flit.metadata.urls]
Documentation = "https://www.cogent3.org/"
"Bug Tracker" = "https://github.com/cogent3/cogent3/issues"
"Source Code" = "https://github.com/cogent3/cogent3"
Changelog = "https://github.com/cogent3/cogent3/blob/develop/changelog.md"

[tool.flit.sdist]
include = ["doc/", "requirements.txt", "src/*", "pyproject.toml"]
exclude = ["doc/*.html"]

[tool.flit.metadata.requires-extra]
test = [
    "black",
    "isort",
    "pytest",
    "pytest-cov",
    "tox"]
doc  = ["click",
        "ipykernel",
        "ipython",
        "ipywidgets",
        "jupyter-sphinx",
        "jupyter_client",
        "jupyterlab",
        "jupytext",
        "kaleido",
        "matplotlib",
        "nbconvert>5.4",
        "nbformat",
        "nbsphinx",
        "numpydoc",
        "pillow",
        "plotly",
        "psutil",
        "sphinx",
        "sphinx-autobuild",
        "sphinx-gallery",
        "sphinx>=1.6",
        "sphinx_bootstrap_theme",
        "sphinx_panels",
        "sphinxcontrib-bibtex"]
extra = ["pandas", "plotly", "psutil", "kaleido"]
dev = ["black",
       "click",
       "flit",
       "ipykernel",
       "ipython",
       "ipywidgets",
       "isort",
       "jupyter-sphinx",
       "jupyter_client",
       "jupyterlab",
       "jupytext",
       "kaleido",
       "matplotlib",
       "nbconvert>5.4",
       "nbformat",
       "nbsphinx",
       "numpydoc",
       "pandas",
       "pillow",
       "plotly",
       "psutil",
       "pytest",
       "pytest-cov",
       "sphinx",
       "sphinx-autobuild",
       "sphinx-gallery",
       "sphinx_bootstrap_theme",
       "sphinx_panels",
       "sphinxcontrib-bibtex",
       "tox"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | doc
  | dist
  | tests/data
)/
'''

[tool.isort]
atomic=true
force_grid_wrap=0
include_trailing_comma=true
lines_after_imports=2
lines_between_types=1
multi_line_output=3
use_parentheses=true
