
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-04-15T12:39:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea728392008abe791edd52da369c132f32c31d0d",
 "version": "1.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
