[tool.poetry]
name = "scm_config"
version = "0.1.4"
description = "self configuration management written in Python"
authors = ["Sai Repalle <n.repalle85@gmail.com>"]

# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Sai-Repalle/scm_project"
repository = "https://github.com/Sai-Repalle/scm_project"
keywords = ["config", "markdown", "lint"]
classifiers = [
    "Environment :: Console",
    "Operating System :: POSIX :: Linux" 
]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.4.1"
colorama = "^0.4.4"
ordered-set = "^4.1.0"
dynaconf = "^3.1.8"
pytest = "^7.1.1"
deepdiff = "^5.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scm = 'scm_config.main:main_cli'

