[tool.poetry]
name = "pybased"
version = "0.0.1"
description = "Library for creating arbitrary binary encodings.  Includes variations on base32, base64, base85, and more."
authors = ["Rob Nelson <nexisentertainment@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = 'https://gitlab.com/N3X15/python-based'
packages = [
    {include = 'based'}
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
frozendict = "^2.3.2"
tabulate = "^0.8.9"
click = "^8.1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.942"
autopep8 = "^1.6.0"
isort = "^5.10.1"
poetryup = "^0.6.1"
twine = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
