[tool.poetry]
name = "nextchat"
version = "1.0.0.1"
description = "Easy to use bot API for https://replchat.vapwastaken.repl.co/"
authors = ["Bleekpie"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
