
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-23T12:44:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb03ff5477e3972b2b50b5eca5b56428d364a1a2",
 "version": "1.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
