[tool.poetry]
name = "gpr-algorithm"
version = "0.0.1a"
description = "Gene Programming Rules (GPR) implementation"
authors = [
    "Anna Czmil <czmilanna@gmail.com>",
    "Sylwester Czmil <sylwekczmil@gmail.com>",
    "Jacek Kluska <jacklu@prz.edu.pl>"
]
readme = "README.rst"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
deap = "1.3.1"
geppy = "0.1.3"
graphviz = "0.19.1"
numpy = "1.21.5"
scikit-learn = "1.0.1"
sympy = "1.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
cacp = "^0.1.4"
tox = "^3.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
