[tool.poetry]
name = "makehash"
version = "0.1.5"
description = "A CLI tools use to create *.hash file and verify it later."
authors = [ "Cologler <skyoflw@gmail.com>" ]
readme = "README.md"

  [tool.poetry.scripts]
  makehash = 'makehash.entry_points_console_scripts:makehash'
  verifyhash = 'makehash.entry_points_console_scripts:verifyhash'

  [tool.poetry.dependencies]
  python = "^3.9"
  fsoopify = "*"
  click-anno = "*"
  colorama = "*"
  alive-progress = "*"

  [tool.poetry.dev-dependencies]
  pytest = "^6.2.5"
  pytest-cov = "^2.12.1"
  pyinvoke = "^1.0.4"

[tool.poetry-dynamic-versioning]
enable = false

[build-system]
requires = [ "poetry-core>=1.0.0", "poetry-dynamic-versioning" ]
build-backend = "poetry.core.masonry.api"
