
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-17T03:18:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e587e82a4085d0c0a4541f61e49b7b748c631da6",
 "version": "v3.1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
