[build-system]
requires = ["setuptools>=42","certifi==2021.10.8","charset-normalizer==2.0.12","idna==3.3","log4mongo==1.7.0","pymongo==4.1.1","python-dateutil==2.8.2","requests==2.27.1","six==1.16.0","termcolor==1.1.0","urllib3==1.26.9"]
build-backend = "setuptools.build_meta"
