
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T15:32:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "588f695b373f02191a377f12536e918492c1621d",
 "version": "2.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
