# coding: utf-8

"""
    Emby Server API

    Explore the Emby Server API  # noqa: E501

    OpenAPI spec version: 4.6.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import EmbyAPI
from EmbyAPI.models.live_tv_guide_info import LiveTvGuideInfo  # noqa: E501
from EmbyAPI.rest import ApiException


class TestLiveTvGuideInfo(unittest.TestCase):
    """LiveTvGuideInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiveTvGuideInfo(self):
        """Test LiveTvGuideInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmbyAPI.models.live_tv_guide_info.LiveTvGuideInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
