# coding: utf-8

"""
    Emby Server API

    Explore the Emby Server API  # noqa: E501

    OpenAPI spec version: 4.6.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import EmbyAPI
from EmbyAPI.api.official_rating_service_api import OfficialRatingServiceApi  # noqa: E501
from EmbyAPI.rest import ApiException


class TestOfficialRatingServiceApi(unittest.TestCase):
    """OfficialRatingServiceApi unit test stubs"""

    def setUp(self):
        self.api = EmbyAPI.api.official_rating_service_api.OfficialRatingServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_officialratings(self):
        """Test case for get_officialratings

        Gets items based on a query.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
