# coding: utf-8

"""
    Emby Server API

    Explore the Emby Server API  # noqa: E501

    OpenAPI spec version: 4.6.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import EmbyAPI
from EmbyAPI.models.dlna_subtitle_profile import DlnaSubtitleProfile  # noqa: E501
from EmbyAPI.rest import ApiException


class TestDlnaSubtitleProfile(unittest.TestCase):
    """DlnaSubtitleProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDlnaSubtitleProfile(self):
        """Test DlnaSubtitleProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmbyAPI.models.dlna_subtitle_profile.DlnaSubtitleProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
