
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T20:29:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ec4e9bad471fb34bfed7ff468e3856c8b0daa5d",
 "version": "0.0.75.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
