[project]
name = "colassigner"
dynamic = ["version", "description"]
authors = [{name = "Endre Márk Borza", email = "endremborza@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.optional-dependencies]
test = ["branthebuilder", "pandas"]
doc = [
    "sphinx",
    "pandoc",
    "graphviz",
    "sphinx-automodapi",
    "sphinx-rtd-theme",
    "myst-parser",
    "pygments",
    "jupyter",
    "toml"
]

[project.urls]
Homepage = "https://github.com/endremborza/colassigner"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.branb]
line-length = 88
