[tool.poetry]
name = "countdown-tddschn"
version = "0.2.2"
description = ""
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]

[tool.poetry.scripts]
scd = "countdown_tddschn.bin.simple_countdown:app"

[tool.poetry.dependencies]
python = "^3.10"
pync = "^2.0.3"
typer = "^0.4.1"
python-daemon = "^2.3.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.32.0"
bump2version = "^1.0.1"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
