[tool.poetry]
name = "euler-math"
version = "0.4.5"
description = "Utilities for Project Euler"
authors = ["David Carlson <mndrake2222@gmail.com>"]

license = "MIT"
readme = "README.md"

homepage = "https://github.com/mndrake/euler-math"
repository = "https://github.com/mndrake/euler-math"

keywords = ["math", "euler"]

classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Mathematics',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3'
    ]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
gmpy2 = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"
twine = "^4.0.0"
pylint = "^2.13.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
