[tool.poetry]
name = "fable-library"
version = "0.6.0"
description = "Fable library for Python"
authors = ["Dag Brattli <dag@brattli.net>"]
license = "MIT License"
readme = "README.md"
homepage = "https://fable.io"
include = ["fable_library/**/*"] # Poetry excludes build from .gitignore

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
expression = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
