[tool.poetry]
name = "salix-containers"
version = "0.2.0"
description = "Occasionally handy container types"
authors = ["Salix <salix@pilae.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
jmespath = "^1.0.0"
salix-jmespath-tools = "^0.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
