py_install = "`pvx py install \[-f] \[VERSION]`"
py_archive = "`pvx py archive \[VERSION]`"
py_romove = "`pvx py remove \[VERSION]`"
py_list = "`pvx py list`"
py_python_build = "`git clone https://github.com/pyenv/pyenv.git ~/.pyenv`"
