
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T17:07:16-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "246b3463dfd0e163f635b84e455e350c55834520",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
