[tool.poetry]
name = "voltfpipe"
version = "0.1.0"
description = "A pipeline manager for a voltf project (photogrammetry and videogrammetry)"
authors = ["Luke Miller <dodgyville@gmail.com>"]
license = "GPLv3+"
homepage = "https://gitlab.com/dodgyville/voltfpipe"
repository = "https://gitlab.com/dodgyville/voltfpipe"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.1"
dataclasses-json = "^0.5.7"
"ruamel.yaml" = "^0.17.21"
slug = "^2.0"
simple-term-menu = "^1.4.1"
pypsxlib = "^0.2.0"
opencv-python = "^4.5.5"


[tool.poetry.scripts]
voltfpipe = "voltfpipe.cli:app"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
