
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T16:58:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d22dd6fe44a9f2444ced291f49a50ecac60fb24a",
 "version": "1.0.0-alpha"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
