[tool.poetry]
name = "factorytools"
version = "0.1.0"
description = "Assistive tools for factoryboy"
authors = ["Jayson Dorsett <ja_dorsett@jdorsett.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.0"
factory_boy = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^7"
pytest-django = "^4.5"

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
