
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T10:36:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5a0b4d62f6d69fe4913d709d7f60d774cfc4ab4",
 "version": "v3.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
