[tool.poetry]
name = "smsdrop-python"
version = "1.0.0"
description = "A python sdk for the smsdrop.net platform"
authors = ["Tobi DEGNON <tobidegnon@protonmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Tobi-De/smsdrop-python"
homepage = "https://github.com/Tobi-De/smsdrop-python"
keywords = ["Sdk", "Sms", "Api", "Smsdrop", "Campaign"]
packages = [
    { include = "smsdrop" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.22.0"
mkdocs-material = "^8.2.9"
mkdocstrings = "^0.18.1"
mkdocs-material-extensions = "^1.0.3"
mkdocs = "^1.3.0"
mkdocs-include-markdown-plugin = "^3.3.0"
redis = { version = "4.2.2", optional = true }
tenacity = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
mypy = "^0.942"
flake8 = "^4.0.1"
isort = "^5.10.1"
python-dotenv = "^0.20.0"
bpython = "^0.22.1"
pytz = "^2022.1"
black = "^22.3.0"
pre-commit = "^2.18.1"
Faker = "^13.3.4"
poetryup = "^0.6.1"
pytest-httpx = "^0.20.0"

[tool.poetry.extras]
redis = ["redis"]

[tool.black]
line-length = 79
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 88
force_grid_wrap = 0
ensure_newline_before_comments = true
py_version = 27

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
