[default]
__title__="gytrash"
__description__="Useful things for Logging."
__url__="http://github.com/trejas/gytrash"
__version__="0.0.21"
__author__="Traey Hatch"
__author_email__="thatch@newmathdata.com"
__license__="Apache 2.0"
__copyright__="Copyright 2020 New Math Data"

[tool.isort]
profile="black"