
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T18:05:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7970a59a8a5a37b463e7937fd04893bbc9790276",
 "version": "0.0.75.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
