[tool.poetry]
name = "start_django_project"
version = "2.0.1"
readme = "README.md"
description = "Init a new django project with a simple bootstrap layout"
authors = ["TechHeart <contact@TechHeart.co.uk>"]
license = "MIT"
exclude = ["start_django_project/django-template/venv", "start_django_project/django-template/db.sqlite3", "static/admin", "static/baton", "static/CACHE", "static/rest_framework"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start-django-project = 'start_django_project.cli:cli'
