VERSION_YEAR = 2022
VERSION_MONTH = int('04')
VERSION_DAY = int('21')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('10')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202204210210
version_date = '2022/04/21 02:10'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
