# Generated by Django 3.2.12 on 2022-03-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaddress',
            name='zipcode',
        ),
    ]
