# Generated by Django 3.2.12 on 2022-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0005_auto_20220328_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('branch_office', 'Branch Office'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('drop_shipping', 'Dropshipping'), ('deliverable', 'Deliverable'), ('else', 'Else')], default='billing', help_text='E.g. Shipping or billing', max_length=255, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='linkedaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
