
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-24T02:31:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e8e6a52f5268043c4a376d61a42ee872f7f0b44",
 "version": "0.9.dev2217"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
