[tool.poetry]
name = "badut"
version = "0.1.0"
description = "Python HTTP client designed to be simple in async context"
authors = ["sinkaroid <anakmancasan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["badut", "badut.utils"]
