[tool.poetry]
name = "polysynth"
version = "0.7.2"
description = "Official Python wrapper for the Polysynth platform"
repository = "https://github.com/kryptolabs/polysynth-python"
readme = "README.md"
keywords = ["polysynth", "ethereum", "polygon", "trading"]
authors = ["Polysynth <bugs@polysynth.com>"]
license = "MIT"
packages = [
    { include = "polysynth" },
]
include = ["poylsynth/assets/*.json"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.scripts]
polypy = "polysynth:main"

[tool.poetry.dependencies]
python = "^3.7.2"
web3 = "^5.24.0"
beartype = "^0.8.0"
pickleDB = "^0.9.2"

[tool.poetry.dev-dependencies]
mypy = "*"
black = "*"
pytest = "^6.0"
pytest-cov = "*"
pytest-dotenv = "*"
python-dotenv = "*"
flake8 = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
