"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeCRMClient
from MergeCRMClient.model.opportunity_status_enum import OpportunityStatusEnum


class TestOpportunityStatusEnum(unittest.TestCase):
    """OpportunityStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpportunityStatusEnum(self):
        """Test OpportunityStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpportunityStatusEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
