"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeCRMClient
from MergeCRMClient.model.stage import Stage
globals()['Stage'] = Stage
from MergeCRMClient.model.paginated_stage_list import PaginatedStageList


class TestPaginatedStageList(unittest.TestCase):
    """PaginatedStageList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedStageList(self):
        """Test PaginatedStageList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedStageList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
