"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeCRMClient
from MergeCRMClient.model.multipart_form_field_request import MultipartFormFieldRequest


class TestMultipartFormFieldRequest(unittest.TestCase):
    """MultipartFormFieldRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultipartFormFieldRequest(self):
        """Test MultipartFormFieldRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultipartFormFieldRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
