"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeCRMClient
from MergeCRMClient.model.contact import Contact
from MergeCRMClient.model.debug_mode_log import DebugModeLog
from MergeCRMClient.model.error_validation_problem import ErrorValidationProblem
from MergeCRMClient.model.warning_validation_problem import WarningValidationProblem
globals()['Contact'] = Contact
globals()['DebugModeLog'] = DebugModeLog
globals()['ErrorValidationProblem'] = ErrorValidationProblem
globals()['WarningValidationProblem'] = WarningValidationProblem
from MergeCRMClient.model.crm_contact_response import CRMContactResponse


class TestCRMContactResponse(unittest.TestCase):
    """CRMContactResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCRMContactResponse(self):
        """Test CRMContactResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CRMContactResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
