[tool.poetry]
name = "directbank"
version = "1.0.2"
description = ""
authors = ["Toony <kizyanov@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/kizyanov/directbank"
repository = "https://gitlab.com/kizyanov/directbank"
keywords = ["directbank"]
classifiers = [
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

include = [
    "LICENSE",
]

packages = [
    { include = "directbank", from = 'src'},
]

[tool.poetry.dependencies]
python = "^3.9"
xsdata = "22.4"

[tool.poetry.dev-dependencies]
pytest = "7.1.1"
pytest-cov = "3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
