
[tool.poetry]
name = "athena_tools"
version = "0.0.1"
description = "set of useful Athena db creation tools"
authors = ["stephen bias <stephen.bias@digital.justice.gov.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
pydbtools = "^5.2.0"
mojap-metadata = {version = "^1.9.4", extras = ["glue", "arrow"]}
dataengineeringutils3 = "^1.4.0"
arrow-pd-parser = "^1.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
