
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T07:51:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "22f0df27d4e05efaf5f2dc7ea03baa6fd856cfb6",
 "version": "0.10.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
