[tool]

[tool.poetry]
name = "shatail"
version = "0.1.1"
homepage = "https://github.com/llango/shatail"
description = "根据Wagtail修改的Django CMS 系统。"
authors = ["Rontomai <rontomai@gmail.com>"]
readme = "README.md"
license =  "BSD-3-Clause"
classifiers=[
    'License :: OSI Approved :: BSD License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
include = [
    "LICENSE",
    "shatail/py.typed"
]

[tool.poetry.dependencies]
python = "^3.7"
importlib_metadata = "^3.4.0"

[tool.poetry.dev-dependencies]
mkdocs-material = "^6.1.5"
pytest = "^6.0"
pytest-cov = "^2.10.1"
shadocs = "^0.1.3"

pylint = "^2.6.0"
black = "20.8b1"
mypy = "0.790"

[tool.black]
line-length=100

[tool.pylint.reports]
output-format="colorized"
reports="y"
include-ids="yes"
msg-template="{msg_id}:{line:3d},{column}: {obj}: {msg}"

[tool.pytest.ini_options]
addopts = "--cov=shatail --cov-branch --cov-report term-missing  -vv --color=yes --cov-fail-under 100"
python_files = "tests.py test_*.py *_tests.py"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# 用于执行
[tool.poetry.scripts]
shatail = 'shatail.bin.shatail:main'
