
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T20:09:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "82e05475255284d1cf59fc1ef596ff2da0d86a10",
 "version": "2.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
