[tool.poetry]
name = "bctf"
version = "22.04.18-11"
description = "(WIP) Run own commands before commit / push etc"
authors = ["Tadeusz Miszczyk <42252259+8tm@users.noreply.github.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
bctf = 'bctf.main:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
