
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T12:52:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c7598f324efa42ec7148779075fc978c66fa499",
 "version": "2653"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
