[tool.poetry]
name = "flashpass"
version = "0.1.3"
description = "Encrypt & Decrypt FlashPass .fp files"
authors = ["Carson Mullins <carsonmullins@yahoo.com>"]
license = "GPL-2.0-only"
readme = "README.rst"
repository = "https://github.com/Septem151/flashpass"
keywords = ["security", "passwords"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: End Users/Desktop",
  "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Security",
  "Topic :: Utilities",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.10"
cryptography = "^36.0.2"
pyperclip = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
pylint = "^2.13.7"
mypy = "^0.942"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = "C0330, C0326, W0511"

[tool.pylint.format]
max-line-length = "88"


[tool.poetry.scripts]
flashpass = "flashpass.cli:main"
