[tool.poetry]
name = "anytype"
version = "0.0.0"
description = "Preserving a name for anytype.io library for Python,"
authors = ["Bobronium <appkiller16@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
