[tool.poetry]
name = "sdd-segmentation"
version = "0.1.0-alpha.1"
description = "The python implementation of algorithm proposed by Z. Wang, 'A New Approach for Segmentation and Quantification of Cells or Nanoparticles,' in IEEE Transactions on Industrial Informatics, vol. 12, no. 3, pp. 962-971, June 2016, DOI: 10.1109/TII.2016."
authors = ["Aleksandr Sinitca <siniza.s.94@gmail.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://gitlab.com/digiratory/sdd-segmentation"

packages = [
    { include = "sdd_segmentation" },
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.0"
scipy = "^1.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
