
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T14:34:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ce1ab513f3d7d85016969d90bb1bb9e62451d53",
 "version": "0.1.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
