from enum import Enum


class Language(Enum):
    AUTO = "auto"
    BULGARIAN = "bg"
    CHINESE = "zh"
    CZECH = "cs"
    DANISH = "da"
    DUTCH = "nl"
    ENGLISH = "en"
    ESTONIAN = "et"
    FINNISH = "fi"
    FRENCH = "fr"
    GERMAN = "de"
    GREEK = "el"
    HUNGARIAN = "hu"
    ITALIAN = "it"
    JAPANESE = "ja"
    LATVIAN = "lv"
    LITHUANIAN = "lt"
    POLISH = "pl"
    PORTUGUESE = "pt"
    ROMANIAN = "ro"
    RUSSIAN = "ru"
    SLOVAK = "sk"
    SLOVENIAN = "sl"
    SPANISH = "es"
    SWEDISH = "sv"
