[tool.poetry]
authors = ["Tommaso Amici <me@tommasoamici.com>"]
license = "MIT"
name = "wagtail-redisearch"
description = "A Django app to use RediSearch as a search backend in Wagtail."
version = "0.4.0"
readme = "README.md"
repository = "https://github.com/TommasoAmici/wagtail-redisearch"
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Django",
  "Framework :: Django :: 3.2",
  "Framework :: Django :: 4",
  "Framework :: Wagtail",
  "Framework :: Wagtail :: 2"
]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^4.0 || ^3.2"
redis = "^4.0.0"
wagtail = "^2.15"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3.0"
pycodestyle = "^2.8.0"
pre-commit = "^2.18.1"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
  "-ra",
  "-q",
  "--doctest-modules",
  "--cov",
  "--cov-branch",
  "--cov-report=term-missing",
  "--cov-report=xml:coverage.xml",
  "--ds=integration.example.settings"
]
testpaths = ["tests", "wagtail_redisearch"]

[tool.coverage.report]
omit = ["*/tests/*", "*/integration/*"]

[tool.isort]
multi_line_output = 3
known_django = "django"
known_wagtail = "wagtail"
sections = "FUTURE,STDLIB,DJANGO,WAGTAIL,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
