[tool.poetry]
name = "js.typeahead"
version = "0.11.1"
description = "Fanstatic Package of Twitter's Typeadhead.js"
authors = ["Manuel Vázquez Acosta <manuel@merchise.org>"]
license = "MIT"
packages = [
   { include="js/**/*" },
]
homepage = "https://gitlab.com/merchise-autrement/js.typeahead"


[tool.poetry.dependencies]
python = ">=3.8,<4.0"
"js.jquery" = "^3.3.1"
fanstatic = "^1.2"

[tool.poetry.dev-dependencies]
black = "22.3.0"
flake8 = "^4.0.1"
isort = "5.10.1"
mypy = "0.942"
flake8-bugbear = "22.3.23"
pytest = "^7.1.1"
"xotl.tools" = "^2.2.4"

[tool.poetry.plugins."fanstatic.libraries"]
js_typeahead = "js.typeahead:lib"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 80
target-version = ['py38']
