from edgeiq._production_client import PRODUCTION_CLIENT as PRODUCTION_CLIENT
from edgeiq.edge_tools import to_json_serializable as to_json_serializable
from typing import Any

class BarcodeDetectionPrediction:
    def __init__(self, box, barcode_type, info) -> None: ...
    def __eq__(self, other): ...
    @property
    def box(self): ...
    @property
    def barcode_type(self): ...
    @property
    def info(self): ...

class BarcodeDetectionResults:
    def __init__(self, predictions, image) -> None: ...
    def __eq__(self, other): ...
    @property
    def predictions(self): ...
    @property
    def image(self): ...
    def markup_image(self): ...
    def crop_localized(self): ...

RESULT_TYPE: Any

class BarcodeDetection:
    barcode_detector: Any
    def __init__(self) -> None: ...
    def localize_decode(self, image): ...
    def localize(self, image): ...
    def decode(self, image, boxes): ...
    def publish_analytics(self, results, tag: Any | None = ...) -> None: ...
