from edgeiq import edge_tools as edge_tools, runtime as runtime
from edgeiq.constants import Accelerator as Accelerator, Engine as Engine, HAILO_SUPPORTED_OS as HAILO_SUPPORTED_OS, MYRIAD_SUPPORTED_OS as MYRIAD_SUPPORTED_OS
from typing import Any

def get_opencv_engine(engine): ...
def get_opencv_accelerator(accelerator): ...

SUPPORTED_ACCELERATOR: Any
SUPPORTED_OPENCV_ENGINE: Any
HAILO_SUPPORTED_ARCHITECTURES: Any

def validate_engine_accelerator_pair(engine, accelerator, model_config): ...

class BaseService:
    def __init__(self, model_config) -> None: ...
    def load(self, engine=..., accelerator=...) -> None: ...
    @property
    def labels(self): ...
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, colors) -> None: ...
    @property
    def model_id(self): ...
    @property
    def engine(self): ...
    @property
    def accelerator(self): ...
    @property
    def model_purpose(self): ...
