# Generated by Django 3.2.12 on 2022-03-21 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('simpel_themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltemplate',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simpelpages', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.CreateModel(
            name='ScreenShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Caption')),
                ('thumb_height', models.IntegerField(default=100, verbose_name='Thumbnail Height')),
                ('thumb_width', models.IntegerField(default=100, verbose_name='Thumbnail Width')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_screenshoots', to=settings.FILER_IMAGE_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='screenshoots', to='simpel_themes.modeltemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'Template Screenshoot',
                'verbose_name_plural': 'Template Screenshoots',
                'index_together': {('template', 'image')},
            },
        ),
    ]
