[tool.poetry]
name = "ready_logger"
version = "0.1.2"
description = "Easily configure loggers."
authors = ["Dan Kelleher <dan@danklabs.org>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
