# Generated by Django 2.0 on 2018-02-15 10:50

from django.db import migrations
import shatail.blocks
import shatail.fields
import shatail.test.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0028_headcountrelatedmodelusingpk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body",
            field=shatail.fields.StreamField(
                (
                    ("text", shatail.blocks.CharBlock()),
                    ("rich_text", shatail.blocks.RichTextBlock()),
                    ("image", shatail.test.testapp.models.ExtendedImageChooserBlock()),
                    (
                        "product",
                        shatail.blocks.StructBlock(
                            (
                                ("name", shatail.blocks.CharBlock()),
                                ("price", shatail.blocks.CharBlock()),
                            )
                        ),
                    ),
                )
            ),
        ),
    ]
