
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-17T18:20:41-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3efc7d01fa4a14a989c7cf9a3b78417101b8614d",
 "version": "5.8.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
