[tool.poetry]
name = "royalnet-console"
version = "6.6.2"
description = "A terminal-based frontend for the royalnet.engineer module."
authors = ["Stefano Pigozzi <me@steffo.eu>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/Steffo99/royalnet-console"
documentation = "https://royalnet-console.readthedocs.io/"
keywords = ["royalnet"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Topic :: Terminals",
]

[tool.poetry.dependencies]
python = "^3.8"
royalnet = "~6.6.0"
psutil = "^5.8.0"
click = "^7.1.2"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pytest-asyncio = "^0.15.0"
sphinx = "^3.3.1"
sphinx_rtd_theme = "^0.5.0"

[tool.pytest.ini_options]
minversion = "6.0"
log_cli = true
log_cli_level = "DEBUG"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
