[tool.poetry]
name = "anyioc"
version = "0.12.1"
description = "Another simple ioc framework for python"
authors = [ "Cologler <skyoflw@gmail.com>" ]
license = "MIT"
readme = "README.md"

  [tool.poetry.dependencies]
  python = "^3.7"

  [tool.poetry.dev-dependencies]
  type-info = "^0.0.2"
  pytest = "^6.2.4"
  pytest-cov = "^2.12.1"

[tool.poetry-dynamic-versioning]
enable = false

[build-system]
requires = [ "poetry-core>=1.0.0", "poetry-dynamic-versioning" ]
build-backend = "poetry.core.masonry.api"
