[build-system]
requires = [
    "setuptools>=42.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.bandit]
exclude_dirs = ["venv"]
skips = ["B101"]

[tool.black]
line_length = 119
target_version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 39
line_length = 119

[tool.pytest.ini_options]
addopts = "-ra --verbose"
testpaths = ["test"]

[tool.coverage.run]
branch = true
omit = ["reddit_sauce_harvester/__main__.py"]
source = ["reddit_sauce_harvester"]

[tool.coverage.report]
show_missing = true
exclude_lines = ["if __name__ == .__main__.:"]
