# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ed/stdcom/src/stdcom/pjanice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pjanice(object):
    def setupUi(self, pjanice):
        pjanice.setObjectName("pjanice")
        pjanice.resize(376, 471)
        self.groupBox = QtWidgets.QGroupBox(pjanice)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 316, 145))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditIpAddress = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIpAddress.sizePolicy().hasHeightForWidth())
        self.lineEditIpAddress.setSizePolicy(sizePolicy)
        self.lineEditIpAddress.setObjectName("lineEditIpAddress")
        self.horizontalLayout_2.addWidget(self.lineEditIpAddress)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEditServicePort = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditServicePort.sizePolicy().hasHeightForWidth())
        self.lineEditServicePort.setSizePolicy(sizePolicy)
        self.lineEditServicePort.setMinimumSize(QtCore.QSize(2, 0))
        self.lineEditServicePort.setObjectName("lineEditServicePort")
        self.horizontalLayout.addWidget(self.lineEditServicePort)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonConfigure = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonConfigure.setObjectName("pushButtonConfigure")
        self.horizontalLayout_3.addWidget(self.pushButtonConfigure)
        spacerItem1 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(pjanice)
        QtCore.QMetaObject.connectSlotsByName(pjanice)

    def retranslateUi(self, pjanice):
        _translate = QtCore.QCoreApplication.translate
        pjanice.setWindowTitle(_translate("pjanice", "pjanice"))
        self.groupBox.setTitle(_translate("pjanice", "Multiverse Parameters"))
        self.label.setText(_translate("pjanice", "Multiverse Host"))
        self.lineEditIpAddress.setInputMask(_translate("pjanice", "000.000.000.000;_"))
        self.label_2.setText(_translate("pjanice", "Port"))
        self.pushButtonConfigure.setText(_translate("pjanice", "&Configure"))
