# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"WarcFileRecord": "01_query.ipynb",
         "get_warc_url": "01_query.ipynb",
         "get_warc_timestamp": "01_query.ipynb",
         "get_warc_mime": "01_query.ipynb",
         "get_warc_status": "01_query.ipynb",
         "get_warc_digest": "01_query.ipynb",
         "WarcFileQuery": "01_query.ipynb",
         "header_and_rows_to_dict": "01_query.ipynb",
         "mimetypes_to_regex": "01_query.ipynb",
         "query_wayback_cdx": "01_query.ipynb",
         "IA_CDX_URL": "01_query.ipynb",
         "CaptureIndexRecord": "01_query.ipynb",
         "wayback_url": "01_query.ipynb",
         "fetch_wayback_content": "01_query.ipynb",
         "WaybackRecord": "01_query.ipynb",
         "WaybackQuery": "01_query.ipynb",
         "wayback_fetch_parallel": "01_query.ipynb",
         "WaybackRecord.fetch_parallel": "01_query.ipynb",
         "get_cc_indexes": "01_query.ipynb",
         "parse_cc_crawl_date": "01_query.ipynb",
         "cc_index_by_time": "01_query.ipynb",
         "jsonl_loads": "01_query.ipynb",
         "CC_PAGE_SIZE": "01_query.ipynb",
         "query_cc_cdx_num_pages": "01_query.ipynb",
         "query_cc_cdx_page": "01_query.ipynb",
         "CC_API_FILTER_BLACKLIST": "01_query.ipynb",
         "fetch_cc": "01_query.ipynb",
         "CC_DATA_URL": "01_query.ipynb",
         "CommonCrawlRecord": "01_query.ipynb",
         "CommonCrawlQuery": "01_query.ipynb",
         "cc_fetch_parallel": "01_query.ipynb",
         "CommonCrawlRecord.fetch_parallel": "01_query.ipynb",
         "Process": "02_runners.ipynb",
         "RunnerMemory": "02_runners.ipynb",
         "minibatch": "02_runners.ipynb",
         "compress_encode": "02_runners.ipynb",
         "compress_decode": "02_runners.ipynb",
         "RunnerCached": "02_runners.ipynb",
         "sha1_digest": "03_util.ipynb",
         "URL": "03_util.ipynb",
         "make_session": "03_util.ipynb"}

modules = ["core.py",
           "query.py",
           "runners.py",
           "util.py"]

doc_url = "https://EdwardJRoss.github.io/webrefine/"

git_url = "https://github.com/EdwardJRoss/webrefine/tree/master/"

def custom_doc_links(name): return None
