
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T14:29:41+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4117ef7fb485fe684d86851b845e08a4d89a6bc4",
 "version": "1.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
