---
kind: pipeline
name: python3.7

steps:
- name: build
  image: python:3.7
  commands:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - ls -l dist

- name: install sdist
  image: python:3.7
  commands:
    - ls -l dist
    - pip install dist/veins_gym-*.tar.gz

- name: install bdist_wheel
  image: python:3.7
  commands:
    - pip install dist/veins_gym-*.whl

---
kind: pipeline
name: python3.8

steps:
- name: build
  image: python:3.8
  commands:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - ls -l dist

- name: install sdist
  image: python:3.8
  commands:
    - ls -l dist
    - pip install dist/veins_gym-*.tar.gz

- name: install bdist_wheel
  image: python:3.8
  commands:
    - pip install dist/veins_gym-*.whl

---
kind: pipeline
name: python3.9

steps:
- name: build
  image: python:3.9
  commands:
    - python setup.py sdist
    - python setup.py bdist_wheel
    - ls -l dist

- name: install sdist
  image: python:3.9
  commands:
    - ls -l dist
    - pip install dist/veins_gym-*.tar.gz

- name: install bdist_wheel
  image: python:3.9
  commands:
    - pip install dist/veins_gym-*.whl
