# Generated by Django 3.2.12 on 2022-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0002_remove_linkedaddress_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaddress',
            name='line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='line 2'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='line_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='line 3'),
        ),
    ]
