# Generated by Django 3.2.12 on 2022-03-27 16:58

from django.db import migrations, models
import simpel_utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0003_auto_20220324_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaddress',
            name='line_2',
            field=simpel_utils.models.fields.NullCharField(max_length=255, verbose_name='line 2'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='line_3',
            field=simpel_utils.models.fields.NullCharField(max_length=255, verbose_name='line 3'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], help_text='Treatment Pronouns for the customer', max_length=64, verbose_name='Title'),
        ),
    ]
