[tool.poetry]
name = "handsfree"
version = "0.1.3"
description = ""
authors = ["xiaojunnuo <xiaojunnuo@qq.com>"]


# Only include cythonized files in final build
include = ["handsfree/**/*.so","handsfree/**/*.pyd"]  # ignored in VCS, so we need to be explicit
exclude = ["handsfree/**/*.py","handsfree/**/*.pyc"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
pywebview = "^3.6.3"
psutil = "^5.9.0"
requests = "^2.27.1"
cython = "^3.0.0a10"
setuptools = "^62.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools~=62.1.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple"
default = true


[tool.poetry.build]
# The allows us to build C extensions (using Cython). Unstable feature
# https://github.com/python-poetry/poetry/issues/2740#issuecomment-666551481
script = "build.py"
generate-setup-file = false