
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T23:27:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d22da4bd4a6d6cc522ff33b14ec0754d45825588",
 "version": "0.0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
