
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T10:09:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bbbaf79fecd3247a346002a03949931f0da6eb2",
 "version": "v2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
