
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T14:28:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "10ad8d938296fb88e40dc1b2ac03838f21a75676",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
