[tool.poetry]
name = "nv-tables"
version = "0.1.2"
description = "Tools for read and write data from and into table files (e.g. xls, xlsx, csv, etc.)"
authors = ["Gustavo Santos <gustavo@next.ventures>"]
license = "MIT"
repository = "https://github.com/gstos/nv-utils"
packages = [{ include = "nv"}]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
    "COPYRIGHT",
    "CHANGELOG.md",
    "README.md"
]

[tool.poetry.dependencies]
python = "^3.10"
openpyxl = { version = "^3.0.9", optional = true }
xlrd = { version = "^2.0.1", optional = true }
xlwt = { version = "^1.3.0", optional = true }
xlutils = { version = "^2.0.0", optional = true }
charset-normalizer = { version = "^2.0.10", optional = true }
pytest = "^7.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
coverage = "^6.2"

[tool.poetry.extras]
xls = ["xlrd", "xlwt", "xlutils"]
xlsx = ["openpyxl"]
detect = ["charset-normalizer"]
all = ["xlrd", "xlwt", "xlutils", "openpyxl", "charset-normalizer"]

[tool.pytest.ini_options]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
