# automatically generated by the FlatBuffers compiler, do not modify

# namespace: isp

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SensorsDict(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorsDict()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorsDict(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SensorsDictBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x49\x53\x50\x46", size_prefixed=size_prefixed)

    # SensorsDict
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorsDict
    def Sensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from communications.isp.Sensor import Sensor
            obj = Sensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorsDict
    def SensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorsDict
    def SensorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SensorsDictStart(builder): builder.StartObject(1)
def Start(builder):
    return SensorsDictStart(builder)
def SensorsDictAddSensors(builder, sensors): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sensors), 0)
def AddSensors(builder, sensors):
    return SensorsDictAddSensors(builder, sensors)
def SensorsDictStartSensorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartSensorsVector(builder, numElems):
    return SensorsDictStartSensorsVector(builder, numElems)
def SensorsDictEnd(builder): return builder.EndObject()
def End(builder):
    return SensorsDictEnd(builder)