
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T18:03:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "30de3c29e86e99e65b090e6d8f9fbcf38307748d",
 "version": "0.7.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
