[tool.poetry]
name = "jsw-nx"
version = "1.0.84"
description = "Next toolkit for python."
authors = ["feizheng <1290657123@qq.com>"]
readme = "README.md"
repository = "https://github.com/aric-pypi/jsw-nx"
homepage = "https://js.work"

[tool.poetry.dependencies]
python = "^3.6"
psutil = "^5.9.0"
"ruamel.yaml" = "^0.17.21"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
