
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-11T09:53:18+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1b898fdf102698d7ff1614653326e2da8e72f5b",
 "version": "0.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
