[tool.poetry]
name = "chrome-local-storage"
version = "0.1.0"
description = "Interact with Chrome local storage"
authors = ["Judson Neer <judson.neer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.0"
trio-chrome-devtools-protocol = "^0.6.0"


[tool.poetry.dev-dependencies]
pytest = "^7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
