# Configuration file for scenario theta

# name of scearnio 
name: alpha
# state definitions
states:
      # Depth at each runoff entry point into sewer network
      - !!python/tuple
        - "J1"
        - depthN
      - !!python/tuple
        - "J2"
        - depthN
      - !!python/tuple
        - "J3"
        - depthN
      - !!python/tuple
        - "J4"
        - depthN
      - !!python/tuple
        - "J5a"
        - depthN
      - !!python/tuple
        - "JC5"
        - depthN
      - !!python/tuple
        - "JC4c"
        - depthN                
      # Depth if the junctions nodes at the sewer inlet into the flow regulators
      - !!python/tuple
        - "R1"
        - depthN
      - !!python/tuple
        - "R2"
        - depthN
      - !!python/tuple
        - "R3"
        - depthN
      - !!python/tuple
        - "R4"
        - depthN
      - !!python/tuple
        - "R5"
        - depthN      
      # Depth at the CSO outfalls
      - !!python/tuple
        - "JC1b"
        - depthN
      - !!python/tuple
        - "JC2"
        - depthN
      - !!python/tuple
        - "JC3a"
        - depthN
      - !!python/tuple
        - "JC4c"
        - depthN
      - !!python/tuple
        - "JC5"
        - depthN
      # Depth at each segment of the stream
      - !!python/tuple
        - "C1a"
        - depthL
      - !!python/tuple
        - "C1b"
        - depthL
      - !!python/tuple
        - "C2"
        - depthL
      - !!python/tuple
        - "C3a"
        - depthL
      - !!python/tuple
        - "C3b"
        - depthL
      - !!python/tuple
        - "C4a"
        - depthL
      - !!python/tuple
        - "C4b"
        - depthL
      - !!python/tuple
        - "C4c"
        - depthL
      - !!python/tuple
        - "C5a"
        - depthL
      - !!python/tuple
        - "C5b"
        - depthL
      # Flowrate at final interceptor pipe connected to WWTP
      - !!python/tuple
        - "I5"
        - flow

# Action space
action_space:
        - "Or1"
        - "Or2"
        - "Or3"
        - "Or4"
        - "Or5"

# Performance Targets
performance_targets:
        # CSO overflow
        - !!python/tuple
          - "W1"
          - flow
        - !!python/tuple
          - "W2"
          - flow
        - !!python/tuple
          - "W3"
          - flow
        - !!python/tuple
          - "W4"
          - flow
        - !!python/tuple
          - "W5"
          - flow
        # flooding
        - !!python/tuple
          - "J1"
          - flooding
        - !!python/tuple
          - "J2"
          - flooding
        - !!python/tuple
          - "J3"
          - flooding
        - !!python/tuple
          - "J4"
          - flooding
        - !!python/tuple
          - "J5a"
          - flooding
        - !!python/tuple
          - "J5b"
          - flooding     
        - !!python/tuple
          - "JC1a"
          - flooding
        - !!python/tuple
          - "JC1b"
          - flooding
        - !!python/tuple
          - "JC2"
          - flooding
        - !!python/tuple
          - "JC3a"
          - flooding
        - !!python/tuple
          - "JC3b"
          - flooding
        - !!python/tuple
          - "JC4a"
          - flooding
        - !!python/tuple
          - "JC4b"
          - flooding
        - !!python/tuple
          - "JC4c"
          - flooding          
        - !!python/tuple
          - "JC5"
          - flooding
        - !!python/tuple
          - "JI1"
          - flooding
        - !!python/tuple
          - "JI2"
          - flooding
        - !!python/tuple
          - "JI3a"
          - flooding
        - !!python/tuple
          - "JI3b"
          - flooding
        - !!python/tuple
          - "JI4"
          - flooding
        - !!python/tuple
          - "JI5"
          - flooding
        - !!python/tuple
          - "R1"
          - flooding
        - !!python/tuple
          - "R2"
          - flooding
        - !!python/tuple
          - "R3"
          - flooding
        - !!python/tuple
          - "R4"
          - flooding
        - !!python/tuple
          - "R5"
          - flooding                                   