from enum import Enum


class MessageType(str, Enum):
    PRINTER_REGISTRATION_MESSAGE = 'PRINTER_REGISTRATION_MESSAGE'
    SENSOR_REGISTRATION_MESSAGE = 'SENSOR_REGISTRATION_MESSAGE'
    JOB_UPDATE_MESSAGE = 'JOB_UPDATE_MESSAGE'
    ACTIVITY_STATUS_UPDATE_MESSAGE = 'ACTIVITY_STATUS_UPDATE_MESSAGE'
    UPDATE_COMMAND_MESSAGE = 'UPDATE_COMMAND_MESSAGE'
