
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-17T02:32:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e96e18a82c665f688d7d7c8a14fcd9bbe5e238de",
 "version": "0.4.dev2216"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
