
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-18T03:22:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cabe9022ff423d1e1fd386e73ca5161143890c7",
 "version": "1.16.0.post.dev394"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
