
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-22T10:59:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "31a852f88fe2b23bb49ea1608111e4f32fd1bb7b",
 "version": "1.101.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
