
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-18T18:51:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1fd33d0834809f7b56b64b0b3b3b09410ba28b9",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
