
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T21:53:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "be9562a6a5638073e0d19ac2f23bbf809c43e499",
 "version": "0.0.75.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
