# Generated by Django 3.2.12 on 2022-03-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0004_auto_20220327_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='linkedaddress',
            name='primary',
        ),
    ]
