# Generated by Django 3.2.13 on 2022-04-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('simpel_contacts', '0008_auto_20220420_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverableaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='linked_object_type',
            field=models.ForeignKey(blank=True, help_text='Linked object type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_addresses', to='contenttypes.contenttype'),
        ),
    ]
