[tool.poetry]
name = "heps_ds_utils"
version = "0.2.0"
description = "A Module to enable Hepsiburada Data Science Team to utilize different tools."
authors = ["FarukBuldur <faruk.buldur@hepsiburada.com>"]
maintainers = ["FıratÖncü <firat.oncu@hepsiburada.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.8, < 3.11"
paramiko = "^2.10.3"
scp = "^0.14.4"
PyHive = "^0.6.5"
pandas = "^1.4.1"
thrift = "^0.15.0"
sasl = "^0.3.1"
thrift-sasl = "^0.4.3"
colorama = "^0.4.4"
google-cloud-bigquery = {extras = ["bqstorage", "pandas"], version = "^3.0.1"}
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pylint = "^2.13.4"
python-dotenv = "^0.20.0"
ipykernel = "^6.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
