version: "3.8"

services:
  # memcached
  memcached-1:
    image: bitnami/memcached
    environment:
      - MEMCACHED_PORT_NUMBER=22122
    ports:
      - "22122:22122"
  memcached-2:
    image: bitnami/memcached
    environment:
      - MEMCACHED_PORT_NUMBER=22123
    ports:
      - "22123:22123"
  memcached-uds:
    image: bitnami/memcached
    command: memcached -s /sockets/freiner.memcached.sock -a 777
    volumes:
      - type: bind
        source: .docker/memcached/
        target: /sockets/

  # redis sentinel
  redis-sentinel-master:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6380
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6380:6380"
  redis-sentinel-slave:
    image: bitnami/redis
    depends_on:
      - redis-sentinel-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6381
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-sentinel-master
      - REDIS_MASTER_PORT_NUMBER=6380
    ports:
      - "6381:6381"
  redis-sentinel:
    image: bitnami/redis-sentinel
    depends_on:
      - redis-sentinel-master
      - redis-sentinel-slave
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_SET=localhost-redis-sentinel
      - REDIS_MASTER_HOST=redis-sentinel-master
      - REDIS_MASTER_PORT_NUMBER=6380
    ports:
      - "26379:26379"

  # redis basic
  redis-basic:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=7379
    ports:
      - "7379:7379"
  redis-auth:
    image: bitnami/redis
    environment:
      - REDIS_PORT_NUMBER=7389
      - REDIS_PASSWORD=sekret
    ports:
      - "7389:7389"
  redis-uds:
    image: bitnami/redis
    command: redis-server --port 0 --unixsocket /sockets/freiner.redis.sock --unixsocketperm 777
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: bind
        source: .docker/redis/
        target: /sockets/
