# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test and publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on: push

jobs:

  build:

    # I am only testing with py37 but travis is Testing the other versions of Python
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: |
          tox -e py37

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Publish pythermalcomfort 📦 to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload dist/*.gz dist/*.whl
