name: raspcuterie
devices:
  input:
    temperature:
      type: AM2302
      degree: celsius
      gpio: 5
  output:
    refrigerator:
      type: relay
      gpio: 6
    heater:
      type: relay
      gpio: 19
    humidifier:
      type: relay
      gpio: 26
    dehumidifier:
      type: relay
      gpio: 13
control:
  default: drying
  active:
    group: drying
    until: 2020-10-10 16:00
  groups:
    drying:
      refrigerator:
        - rule: "Stop cooling"
          expression: "temperature < 21"
          action: "off"
        - rule: "Start cooling"
          expression: "temperature > 21"
          action: "on"
      dehumidifier:
        - rule: "Start"
          expression: "humidity > 77"
          action: "on"
        - rule: "Stop"
          expression: "humidity < 70"
          action: "off"
    fermentation22:
      dehumidifier:
        - rule: "Start heating"
          expression: "humidity < 21"
          action: "on"
        - rule: "Stop heating"
          expression: "temperature > 22"
          action: "off"
    fermentation25:
      dehumidifier:
        - rule: "Start heating"
          expression: "humidity < 25"
          action: "on"
        - rule: "Stop heating"
          expression: "temperature > 25"
          action: "off"