[tool.poetry]
name = "pdfmerge2"
version = "0.1.2"
description = "CLI app that merges PDF files"
authors = ["Gasper3 <trzecik65@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Gasper3/pdf-merger"
repository = "https://github.com/Gasper3/pdf-merger"
keywords = ["pdf", "merge", "pdfmerge", "3.10"]

[tool.poetry.dependencies]
python = "^3.10"
PyPDF2 = "^1.27.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pdfmerge = 'pdfmerge2.app:run'
