[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_absolute = "sentinelhub"
sections = ["FUTURE","STDLIB","THIRDPARTY","ABSOLUTE","LOCALFOLDER"]
line_length = 120

[tool.pytest.ini_options]
markers = [
    "aws_integration: marks AWS integration tests.",
    "geopedia_integration: marks Geopedia integration tests.",
    "sh_integration: marks Sentinel Hub integration tests."
]

[tool.coverage.run]
source = [
    "sentinelhub"
]

[tool.coverage.report]
omit = [
    "config.json",
    ".utmzones.geojson"
]
