
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T10:58:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b138d9f2e7a96a50ff13444274e960e93fb684a",
 "version": "0.1.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
