
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T17:40:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "817bc6b2bee12338e44b518f39fbcbb08a9bbbe1",
 "version": "v3.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
