[tool.poetry]
name = "prepost"
version = "0.1.6"
description = "Pre and Post conditions for functions"
authors = ["pub12 <pubudu79@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
