
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T09:54:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb5f7cfa7bab95a5e5ae753239cb7d477c358617",
 "version": "2650"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
