
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T13:19:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "103c585f2ef55a7e8ec8170bc3d99f6bc0159f67",
 "version": "1.0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
