
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-23T11:31:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bdd6e8e9fcd3e5f1fbaf40149795b82c0d4e8f9",
 "version": "0.23.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
