
# This file was generated by 'versioneer.py' (0.20.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T12:58:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d8b6ccbb9c69601291f64cc603aaf55172ecaa3",
 "version": "0.16.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
