
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-04-21T15:18:56-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "db26247c357d3c70c3cfd7d0f5dcb7d31e778bc0",
 "version": "1.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
