
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-16T05:41:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b91d782a1da586c0b0d54cfa7b0ef421d6721e6b",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
