[tool.poetry]
name = "spadsim"
version = "0.1.0"
description = "This is a 2D Monte Carlo simulator written in Python to model the operation of single-photon avalanche detectors. It simulates the stochastic avalanche multiplication process of charge carriers following the absorption of an input photon; a successful detection event is defined as the avalanche current exceeding a pre-defined threshold. The simulator output can be used to analyse the photon detection efficiency and its timing characteristics. This program does not directly simulate dark noise."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = ">=1.18"
pandas = ">=1.3"
matplotlib = ">=3"
dask = ">=2022.01.1"
distributed = ">=2022.01.1"
tqdm = ">=4.3"
ipykernel = ">=6"
numba = ">=0.55"
bokeh = ">=2.1.1"
ipywidgets = "^7.7.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
tox = "^3.24.5"
flake8 = "^4.0.1"
pylint = "^2.13.4"
coverage = "^6.3.2"
pytest-cov = "^3.0.0"
Sphinx = "<=4.3"
numpydoc = "^1.2.1"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
