# coding: utf-8

"""
    Emby Server API

    Explore the Emby Server API  # noqa: E501

    OpenAPI spec version: 4.6.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import EmbyAPI
from EmbyAPI.models.transcoding_info import TranscodingInfo  # noqa: E501
from EmbyAPI.rest import ApiException


class TestTranscodingInfo(unittest.TestCase):
    """TranscodingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranscodingInfo(self):
        """Test TranscodingInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmbyAPI.models.transcoding_info.TranscodingInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
