
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T10:11:32-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea85431cf30d1d5620f4556894b2058cbbb07139",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
