BTC_FULL_VERSION = "v1.9-160-prod"
BTC_SHORT_VERSION = "latest"
BTC_STAGE = "prod"
BTC_PEP = "1.9.160"
BTC_SRV_FULL_TAG = "brainome/btc_srv:v1.9-160-prod"
BTC_SRV_SHORT_TAG = "brainome/btc_srv:latest"
