
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-20T09:45:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "086d2564b466478cdd09a51ee360287066d7c1f3",
 "version": "1.0.114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
