[tool.poetry]
name = "convert_ms"
version = "0.0.5"
description = "Convert a time units to seconds"
readme = "README.md"
authors = ["Forzy <nikita11tzby@gmail.com>"]
license = "Apache License 2.0"
repository = "https://github.com/Forzy8/convert_ms"
homepage = "https://github.com/Forzy8/convert_ms"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
