
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-21T14:44:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "962e4f9547cf58ce049b7cb5afd77007c12e2ce0",
 "version": "5.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
