# Generated by Django 3.2.13 on 2022-04-20 09:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_contacts', '0007_billingaddress_deliverableaddress_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedaddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='linkedaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, region=None, verbose_name='Phone number'),
        ),
    ]
