
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-19T07:48:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "150bd0cb40635ba160faa58263d3b5631af25e14",
 "version": "v0.1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
